services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: postgres_sprintbms
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_sprintbms
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Enables server mode for predefined connections
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - ./pgadmin_data/servers.json:/pgadmin4/servers.json

volumes:
  postgres_data:
  pgadmin_data:
